### ISSUE TITLE
error when requiring leap_year.rb from the command line without absolute path

### ISSUE THREAD

**Issue by alicetragedy** [rubymonsters/testing-for-beginners#3]
In the section "Separating test code", running `ruby -r leap_year.rb -e "p leap_year?(1996)"` from the command line gives a LoadError. It looks as though ruby tries to find `leap_year.rb` from somewhere in the `$LOAD_PATH`. 
Not sure if that helps, but I'm using rvm, and I've created a special folder to run/create all exercises from the book, which is how I assume a user would do it.

My workaround was to give an absolute path to the file (i.e. `ruby -r "/Users/Laura/path-to-my-folder/leap_year.rb" -e "p leap_year?(1996)"`) or run `ruby -I -r "leap_year.rb" -e "p leap_year?(1996)"`) but I'm not sure if this is the better way to fix it.

**Comment by joecorcoran** [comment]
FWIW, we just had the same issue here at Ruby Monstas. Our solution was also to add `-I .` to the command.

I guess when @svenfuchs wrote the chapter, he was working in a directory that Ruby could already access...

**Comment by carlad** [comment]
fixed with this PR: https://github.com/rubymonsters/testing-for-beginners/pull/5

**Comment by bharatagarwal** [comment]
I can see the fix made in the source code. 

However, when I load the page, http://testing-for-beginners.rubymonstas.org/testing/separation.html, I can still see the command without the `.` added for current directory.
